# Generated by Django 4.2.11 on 2024-03-19 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='company',
            name='foundation',
            field=models.PositiveIntegerField(max_length=4),
        ),
    ]
