# Generated by Django 5.0.6 on 2024-06-01 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_company_status_alter_company_foundation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='foundation',
            field=models.PositiveIntegerField(),
        ),
    ]
